- pyproject.toml
- src/pydase/data_service/state_manager.py
- tests/data_service/test_state_manager.py
Only the properties decorated with @load_state could be changes through the frontend. 
This PR moves the check of the decorator into the `load_state` method of the `StateManager` and fixes the bug.
> fix: only load state properties can be updated

- src/pydase/data_service/state_manager.py
When properties do not have a load_state decorator, a misleading log message was printed (something like "Attribute type of '...' changed from 'str' to 'str'. Ignoring value from JSON file..."). This is now removed. 
This also reduces the log level from info to debug.
> fix: improves debug message for properties (load_state decorator)

- src/pydase/utils/helpers.py
- src/pydase/utils/serializer.py
- tests/utils/test_serializer.py
Serialization of DataService instances was handled by calculating the difference between the attributes of the instance and its base class. This PR fixed this by calculating the difference between the attributes of the instance and the DataService class.
> fixed serialization of class deriving from class which derives from DataService

- pyproject.toml
- src/pydase/data_service/data_service_observer.py
- src/pydase/observer_pattern/observable/observable_object.py
- src/pydase/observer_pattern/observer/observer.py
- tests/data_service/test_data_service_observer.py
Dynamically adding a class instance containing a property to a list used to emit change notifications of this property although the list change wasn't emitted yet. So this code:
```python
class PropertyClass(pydase.DataService):
_name = "Hello"
@property
def name(self) -> str:
"""The name property."""
return self._name
class MyService(pydase.DataService):
def __init__(self) -> None:
super().__init__()
self.channels = []
def toggle_high_voltage(self) -> None:
self.channels = []
self.channels.append(PropertyClass())
self.channels[0]._name = "Hoooo"
```
would emit:
```
2024-02-20 12:23:30.065 | DEBUG    | pydase.data_service.data_service_observer:on_change:43 - 'channels[0].name' changed to 'Hello'
2024-02-20 12:23:30.065 | DEBUG    | pydase.data_service.data_service_observer:on_change:43 - …
```
> Fix: dynamic list entry with property

- src/pydase/server/web_server/sio_setup.py
Dynamically setting an attribute to an enumeration when it was, say, a float before will sometimes result in a broken frontend. The reason is that the serialized enum was not completely emitted - the "enum" key-value pair was missing from the dictionary.
> fixes sio callback when attribute changes to an enum which was not present before

- src/pydase/server/web_server/web_server.py
Starting an application without providing a custom css file resulted in an 404 error. This MR adds a default response now yielding an empty css file.
> feat: add "custom.css" endpoint default Response

- README.md
- src/pydase/components/coloured_enum.py
`pydase.components.ColouredEnum` derives from `enum.Enum`. This means that its keys and values need to be unique. If users want to use a colour for multiple enum keys they should use different colour formats.
> adds note that coloured enum values must be unique

- pyproject.toml
- src/pydase/observer_pattern/observable/observable_object.py
- tests/observer_pattern/observable/test_observable_object.py
Pydase currently has a significant memory leak if a `DataService` contains a dict or a list.
- Handle adding and removing to the mappings in the derived `ObservableObject` classes
- Use weak references in dict/list mappping to avoid memory leak
```python
import json
import time
import pydase
dict_json = """
{
"foo": "bar"
}
"""
class Service(pydase.DataService):
def __init__(self) -> None:
super().__init__()
self.dict_attr = {}
service = Service()
while True:
service.dict_attr = json.loads(dict_json)
time.sleep(0.01)
```
> Fix memory leak in ObservableObject

- src/pydase/observer_pattern/observable/observable_object.py
- tests/observer_pattern/observable/test_observable_dict.py
- tests/observer_pattern/observable/test_observable_object.py
The `_observers` dictionary of the `ObservableObject` keeps track of the observers of the object by mapping the access path to a list of parent objects. 
When an observer is removed, the parent object is removed from the list. If the list is empty afterwards, it is now removed from the dictionary.
> Refactor: remove unused attribute key from observers dict

- src/pydase/data_service/data_service_observer.py
- tests/data_service/test_data_service_observer.py
Changing private or protected attributes after the service has been exposed only worked if the object was serializable. This does not really make sense. We only need to tell dependent properties that this attribute has changed. This PR fixes this by first checking if the attribute is part of a private/protected object before serializing it to compare it to the cached value.
> Fix: allow unserializable objects on priv attrs

- poetry.lock
- pyproject.toml
- src/pydase/components/image.py
This PR removes the Pillow dependency which was used to get the file format of a picture. As we can do this manually, we can leave out this extra dependency.
> removes Pillow dependency, updates Image component

- src/pydase/utils/logging.py
- tests/components/test_number_slider.py
- tests/data_service/test_task_manager.py
- tests/observer_pattern/observable/test_observable.py
- tests/observer_pattern/observable/test_observable_dict.py
- tests/observer_pattern/observable/test_observable_object.py
- tests/utils/test_logging.py
The logging setup of pydase was configuring the root logger. This means other packages were also influenced by the log level set through the environment variable (default `logging.DEBUG`).
> configures pydase's logger only (not root logger anymore)

- frontend/src/components/AsyncMethodComponent.tsx
- frontend/src/components/ButtonComponent.tsx
- frontend/src/components/DictComponent.tsx
- frontend/src/components/EnumComponent.tsx
- frontend/src/components/ImageComponent.tsx
- frontend/src/components/ListComponent.tsx
- frontend/src/components/MethodComponent.tsx
- frontend/src/components/NumberComponent.tsx
- frontend/src/components/SliderComponent.tsx
- frontend/src/components/StringComponent.tsx
- frontend/src/hooks/useRenderCount.ts
- poetry.lock
- pyproject.toml
- src/pydase/server/server.py
- src/pydase/server/web_server/sio_setup.py
- src/pydase/server/web_server/web_server.py
- src/pydase/utils/helpers.py
- src/pydase/utils/logging.py
This PR replaces FastAPI with aiohttp. This allows to run the web server in the same event loop and removes loads of dependencies that are not really required.
> Replace fastapi with aiohttp

- README.md
- docs/user-guide/interaction/Python Client.md
- pyproject.toml
- src/pydase/client/client.py
- tests/client/test_client.py
Users could not communicate with services that have SSL-TLS encryption enabled as the client defaulted to insecure websockets.
Programmatically constructing the URL from user input is error-prone, which is why I chose to let the users type in the URL to the remote service themselves.
The client has to be instantiated like this now:
- on local machine with port 8001:
```python
pydase.Client(url="ws://localhost:8001")
```
- on a different host with SSL-TLS encryption enabled (e.g. through a reverse proxy)
```python
pydase.Client(url="wss://other-host.ch")
```
This assumes that the used port is the standard 443.
> Breaking: changing allowed client arguments

- README.md
- docs/user-guide/interaction/Python Client.md
- src/pydase/client/client.py
Implements a context manager for the pydase client:
```python
import pydase
with pydase.Client(url="ws://localhost:8001) as client:
client.proxy.<my_method>()
```
This PR also fixes an issue on the client where the event loop is already running.
> feat: adds a context manager to the client, fixes running loop issue

- .github/workflows/publish-to-pypi.yaml
Updates github action version of [sigstore](https://github.com/sigstore/gh-action-sigstore-python) and updates multiline input.
> CI: fixing github-release ci job

- pyproject.toml
- src/pydase/task/autostart.py
- tests/task/test_task.py
Fixes #158.
Tasks that had `autostart=False` or were already running were passed to `autostart_nested_services`. This caused the recursion, as tasks have a `__self__` attribute pointing to the containing service.
> fix: defining task without autostart fails

- src/pydase/observer_pattern/observable/observable.py
- src/pydase/observer_pattern/observer/property_observer.py
- src/pydase/task/decorator.py
- src/pydase/task/task.py
- src/pydase/utils/helpers.py
- tests/task/test_task.py
When defining a task on a `DataService` class, formerly a `Task` object was created which replaced the decorated method as a class attribute. This caused errors when using multiple instances of that class, as each instance was referring to the same `Task`. This descriptor class now handles the tasks per instance of the service class.
> fix: controlling tasks of instances derived from same class

- pyproject.toml
- src/pydase/data_service/data_service_observer.py
- src/pydase/utils/helpers.py
- tests/data_service/test_data_service_observer.py
Encoding a dictionary key in a full access path is usually done with single quotes, i.e. when accessing a dictionary key, the full access path will look like `"my_dict['my_key'].some_attribute"`. When changing `some_attr` through the frontend, the key will be encoded in double quotes: `'my_dict["my_key"].some_attribute'`. Thus, I have to perform some normalization.
This PR adds normalization to the `DataServiceObserver`, transforming double quotes into single quotes before comparing to the `property_deps_dict`. (This is the dictionary containing the dependencies of properties -> needed to have automatic updates for python properties objects when their dependencies change.)
> Fix: normalize full access path (for dict keys)

- pyproject.toml
- src/pydase/data_service/data_service.py
Starting a Service containing a task was printing warnings about inheritance. This is now fixed.
> fix: removes inheritance warning for descriptors

- pyproject.toml
- src/pydase/client/client.py
Trying to connect to a pydase service from a jupyter notebook fails, as I am passing async functions to the event loop of jupyter. However, this is somehow blocked. I always have to create a new thread to run the client event loop there.
> Fix: client usage in jupyter notebook

- src/pydase/task/task.py
The task module contained a basic logging configuration. This must have slipped in somehow.
> fix: removes basic configuration of logging system in task module

- pyproject.toml
- src/pydase/utils/logging.py
The logging config configured the default handler to write to stderr instead of stdout. This PR changes the behaviour.
> Fix: logging to stdout

- src/pydase/client/client.py
- src/pydase/client/proxy_class.py
- src/pydase/utils/serialization/serializer.py
- tests/utils/serialization/test_serializer.py
When a pydase service connects to another service and adds the proxy class as an attribute, the proxy was not rendered correctly: read-only properties were not read-only, tasks were not displayed correctly, and methods decorated with the `@frontend` decorator were still not shown.
The problem was that the proxy was serialized on the client side, so valuable information was lost in this process.
This PR changes that behaviour: when the proxy is serialized on the client side, it will actually request the serialized representation from the server.
> Fix: proxy class representation

- docs/user-guide/interaction/Python Client.md
- mkdocs.yml
- src/pydase/client/client.py
- src/pydase/client/proxy_class.py
- tests/client/test_reconnection.py
The changes introduced in #171 can have the effect that the client does not reconnect any more.
This PR updates the client proxy class s.t. it triggers a reconnection when the socketio.AsyncClient has been configured s.t. it does not reconnect itself.
> Feat: update client reconnection

- src/pydase/data_service/data_service.py
Initialising a client was printing a warning (see [here](https://github.com/tiqi-group/pydase/issues/170#issuecomment-2388998205)). This PR fixes this.
> Fix: removes warning message when initialising a Client

- src/pydase/client/proxy_loader.py
- src/pydase/server/web_server/api/v1/application.py
- src/pydase/server/web_server/api/v1/endpoints.py
- src/pydase/server/web_server/sio_setup.py
- tests/client/test_client.py
- tests/server/web_server/api/v1/test_endpoints.py
Asynchronous functions could not be triggered by either client (browser, python, or restapi). This PR adds support for this. The async function will be awaited in the running asyncio event loop.
> Fix: triggering async functions 

- src/pydase/client/client.py
- tests/client/test_client.py
Using the client in a context manager fails as `__exit__` is not implemented. This PR fixes this.
> Fix: client context manager

- src/pydase/components/number_slider.py
This removes mypy type errors when overwriting the properties in a derived class.
> chore: sets number slider type hints to Any

- src/pydase/server/web_server/sio_setup.py
When an exception occurs within a function call, this exception is now printed to stderr. Formerly, you would only get the exception message as a `logger.error`.
> feat: log trace when exception occurs within trigger_method

- src/pydase/data_service/data_service_observer.py
- src/pydase/observer_pattern/observer/property_observer.py
- src/pydase/utils/helpers.py
- tests/data_service/test_data_service_observer.py
This PR removes normalization logic that replaced double quotes with single quotes for attribute paths. This caused issues when calculating property dependencies of objects nested in a dictionary.
> Fix: dict key normalization

- src/pydase/task/decorator.py
- src/pydase/task/task.py
- tests/task/test_task.py
Implements #22 and #193.
This PR adds the following options (inspired by systemd unit services) to the `@task` decorator:
- **`restart_on_failure`**: Configures whether the task should restart if it exits due to an exception (other than `asyncio.CancelledError`). Defaults to `True`.
- **`restart_sec`**: Specifies the delay (in seconds) before restarting a failed task. Defaults to `1.0`.
- **`start_limit_interval_sec`**: Configures a time window (in seconds) for rate limiting task restarts. If the task restarts more than `start_limit_burst` times within this interval, it will no longer restart. Defaults to `None` (disabled).
- **`start_limit_burst`**: Defines the maximum number of restarts allowed within the interval specified by `start_limit_interval_sec`. Defaults to `3`.
- …
> Feat: add more task config options

- docs/user-guide/Tasks.md
- src/pydase/task/decorator.py
- src/pydase/task/task.py
- tests/task/test_task.py
Builds upon #202.
- Adds documentation
- Renames `restart_on_failure` to `restart_on_exception`
> chore: adds task docs, renames restart_on_failure to restart_on_exception

- docs/user-guide/Logging.md
- mkdocs.yml
- src/pydase/server/web_server/api/v1/application.py
- src/pydase/server/web_server/sio_setup.py
- tests/server/web_server/api/v1/test_endpoints.py
- tests/server/web_server/test_sio_setup.py
> feat: add support for enhanced client information logging in socketio server

- src/pydase/server/web_server/web_server.py
When X-Forwarded-Prefix was not set, the X-Forwarded-Proto was also not updated on the index.html file. This MR fixes this.
> fix: serves modified index.html (X-Forwarded-Proto) when X-Forwarded-Prefix is not set

- docs/user-guide/interaction/Python Client.md
- src/pydase/client/client.py
- tests/client/test_client.py
`pydase.Client` objects can now send an X-Client-Id header that will be used in the pydase logs of the server the client is connecting to. The header defaults to "pydase_client" for now.
> client: adds X-Client-Id header to pydase.Client

- src/pydase/server/web_server/sio_setup.py
- src/pydase/utils/logging.py
The default logs are now written to stderr. Only the pydase.server logs are written to stdout as this is the information about the clients and the server.
> Feat: Updates logging handlers

- docs/dev-guide/api.md
- docs/user-guide/Service_Persistence.md
- src/pydase/data_service/data_service_cache.py
- src/pydase/data_service/state_manager.py
- src/pydase/server/server.py
- tests/data_service/test_state_manager.py
Implements #44.
When a filename was provided to the `pydase.Server`, it will periodically save the service state to the specified file. The interval between the save events can be configured using the `autosave_interval` argument passed to the server:
```python
pydase.Server(
service=service,
filename="device_state.json",
autosave_interval=10.0,  # save every 10 seconds
).run()
```
> Feat: autosaving feature

- README.md
- docs/dev-guide/api.md
- docs/user-guide/Logging.md
- src/pydase/utils/logging.py
- tests/utils/test_logging.py
This adds a helper function that can be called to set up the logging configuration for a service with the formatter used by pydase.
> Feat: add logging config helper

- src/pydase/observer_pattern/observable/observable.py
- tests/data_service/test_data_service_observer.py
When an observable is returned by a property, the parent object will be added as an observer to the observable. This fixes #187 and #192.
> fix: correctly handle observable properties

- src/pydase/server/server.py
The web_port argument in the pydase.Server defaults to None now. If it is None, the value from ServiceConfig().web_port will be used. This fixes the issue where users might pass the web port dynamcially and by passing None they want to use the default value.
> feat (config): changes web_port loading

- mkdocs.yml
Changes to mkdocs.yml have not been pushed in #221.
> fix: update mkdocs.yml

- pyproject.toml
- src/pydase/client/client.py
- src/pydase/server/server.py
- src/pydase/utils/helpers.py
- tests/client/test_client.py
- tests/client/test_reconnection.py
- tests/components/test_device_connection.py
- tests/server/web_server/api/v1/test_endpoints.py
- tests/server/web_server/test_sio_setup.py
- tests/task/test_task.py
- tests/utils/serialization/test_serializer.py
These changes ensure that `asyncio` event loops are properly closed after use, preventing resource leaks and warnings like `RuntimeError: Cannot close a running event loop `or `Task was destroyed but it is pending!`. By closing the event loop in both the server and client threads, the system shuts down cleanly. This was mainly observed in tests.
> chore: properly closing event loops in client and server

- .github/workflows/python-package.yml
- docs/user-guide/advanced/SOCKS-Proxy.md
- docs/user-guide/interaction/Python-Client.md
- mkdocs.yml
- poetry.lock
- pyproject.toml
- src/pydase/client/client.py
This merge request adds support for routing `pydase.Client` connections through a SOCKS5 proxy (e.g. created via `ssh -D`). The `proxy_url` parameter allows users to specify a SOCKS5 proxy endpoint. This is useful for connecting to services behind firewalls or SSH gateways. 
The underlying `aiohttp` session is configured with a `ProxyConnector` from `aiohttp_socks` to enable proxy-aware communication.
To use this feature, users must install the optional socks dependency:
```bash
pip install "pydase[socks]"
```
> Feat: add SOCKS5 proxy support to pydase.Client

- src/pydase/client/client.py
When not specifying the proxy_url in `pydase.Client`, the aiohttp_socks dependency is not required. This is now handled by putting the import into the correct place, adding a descriptive log message when the import fails.
> fix: using client without aiohttp_socks dependency does not raise

- src/pydase/observer_pattern/observer/property_observer.py
- tests/data_service/test_data_service_observer.py
This fixes the first problem in issue #230. Given the following example:
```python
import time
import pydase
class TimeDisplay(pydase.DataService):
time_ms = 0.0
@property
def datetime(self) -> str:
return time.ctime(self.time_ms)
if __name__ == "__main__":
pydase.Server(TimeDisplay()).run()
```
the `get_property_dependencies` function correctly matches `time_ms` instead of `time_ms)` now.
> Fix: property dependency function argument

- src/pydase/server/server.py
- src/pydase/utils/helpers.py
The `current_event_loop_exists` function was getting the running event loop to check if there was one. This does not return the event loop set through `asyncio.set_event_loop`, so the tasks did not get the event loop that is later startet by the `pydase.Server`.
This MR updates this function to call `get_event_loop` instead of `get_running_loop` and updates `pydase.Server` s.t. it gets a new event loop on startup, as there shouldn't be any other loop running yet.
> fix: task event loop

- docs/user-guide/interaction/Python-Client.md
- src/pydase/client/client.py
- tests/client/test_client.py
This MR adds the hostname of the client as client_id default. This is used for logging on the server side.
> feat: adds client id default

- src/pydase/server/server.py
Users can overwrite `pydase.Server` to register custom logic after the server startup. For example, you can register a task that interacts with the `socketio.AsyncServer` that is initialised in the web server.
> feat: adds post_startup hook to pydase.Server

- src/pydase/server/server.py
- src/pydase/server/web_server/web_server.py
When passing `enable_web=False` to `pydase.Server`, the service should not display the frontend, but still handle socketio and http requests. This MR properly implements this - previously, this option disabled all of that, making it impossible to interact with the service.
> Fix: enable web argument handling

- src/pydase/utils/logging.py
Before emitting sio events in the SocketIOHandler, I have to check if the loop is actually still running. This caused issues with `pytest` as it was tearing down asyncio tasks and stopping the loop, while the sio handler was still trying to send those logs to the sio clients.
> fix: check if loop is running in SocketIOHandler

- src/pydase/server/server.py
- src/pydase/server/web_server/sio_setup.py
- src/pydase/server/web_server/web_server.py
The `WebServer` can be initialised in the `pydase.Server` constructor without any problems. This would allow users to access it before starting the `pydase.Server`. This is, e.g., useful if you want to perform custom logic using the `socketio.AsyncServer`.
> Refactor: web server initialisation

- .github/workflows/python-package.yml
This MR adds python 3.13 to checked versions in the github workflow
> feat: official support for python 3.13

- docs/user-guide/interaction/Python-Client.md
- src/pydase/client/client.py
- src/pydase/client/proxy_loader.py
Adds methods `get_value`, `update_value`, and `trigger_method` to `pydase.Client`, enabling direct access to the server API without going through the proxy object. This allows more explicit, low-level control over remote service interactions.
> Feat: direct api access client

- .github/workflows/python-package.yml
Potential fix for [https://github.com/tiqi-group/pydase/security/code-scanning/4](https://github.com/tiqi-group/pydase/security/code-scanning/4)
To fix the issue, we will add a `permissions` block at the root level of the workflow. This block will explicitly define the minimal permissions required for the workflow to function. Based on the tasks performed in the workflow (e.g., installing dependencies, running tests, and linting), the `contents: read` permission is sufficient. This ensures that the workflow can read the repository contents but cannot perform any write operations.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 4: Workflow does not contain permissions

- src/pydase/observer_pattern/observer/property_observer.py
When a proxy of a pydase client initialised with `block_until_connected=False` is set as an attribute of a data service, a race condition can happen: when the client connects while the `DataServiceObserver` is being initialised, the `property_deps_dict` attribute might not be set yet while the `DataServiceObserver` was already added as an observer to the client proxy. The proxy will then emit a notification, which in turn tries to get the dependent properties from the `property_deps_dict` attribute, which has not been initialised yet. The resulting exception prevents the proxy to learn that the client has connected.
> fix: race-condition in PropertyObserver

- src/pydase/data_service/data_service.py
- tests/data_service/test_data_service.py
Adding keys to dictionaries trigger this warning, so I would consider this warning to not be useful any more.
> removes _warn_on_type_change from DataService setattr
